import { GoogleOAuthProvider } from '@react-oauth/google';
import AuthProvider from './AuthProvider';
import './globals.css'

import Navbar from "./layout/Navbar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
        <AuthProvider>
          <Navbar />
          <GoogleOAuthProvider clientId={process.env.CLIENT_ID}>
          {children}
          </GoogleOAuthProvider>
        </AuthProvider>
        
      </body>
    </html>
  );
}
