import { GoogleOAuthProvider } from '@react-oauth/google';
import AuthProvider from './AuthProvider';
import './globals.css'

import Navbar from "./layout/Navbar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
      <GoogleOAuthProvider clientId='1012457994239-tsacsh4u34himgkpj1ve9a94dugm0iia.apps.googleusercontent.com'>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
        </GoogleOAuthProvider>
        
      </body>
    </html>
  );
}
