import { GoogleOAuthProvider } from '@react-oauth/google';
import AuthProvider from './AuthProvider';
import './globals.css'

import Navbar from "./layout/Navbar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
      <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_CLIENT_ID}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
        </GoogleOAuthProvider>
        
      </body>
    </html>
  );
}
